# Generated by Django 5.2.5 on 2025-09-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=50)),
                ('listing_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedrooms', models.CharField(blank=True, max_length=10, null=True)),
                ('bathrooms', models.CharField(blank=True, max_length=10, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('full_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('fireplace', models.BooleanField(default=False)),
                ('central_ac', models.BooleanField(default=False)),
                ('security_system', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('smart_home', models.BooleanField(default=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('preferred_contact', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('both', 'Both')], default='both', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
